### ISSUE TITLE
Provide a API documentation

### ISSUE THREAD

**Issue by 0x46616c6b** [systemli/ticker#10]

**Comment by uzzz** [comment]
Hi!

I think ticker software quite interesting and more important - I share the values behind your collective, so I would like to help with it. I could contribute API docs, it'll help me to understand the software and the codebase but first of all I want to make sure no one is working on it yet.

If not I can propose doing API docs using openapi (https://www.openapis.org) spec. What do you think?

**Comment by 0x46616c6b** [comment]
Hey, nice to bring that up. I also had OpenAPI Specs in mind. Do you want to add annotations/comments on the handlers to be autogenerated or do you want to create a custom spec file?

**Comment by uzzz** [comment]
Hey. I was thinking about a custom file, but I don't have any objections against annotations too. What's your opinion on it?

**Comment by 0x46616c6b** [comment]
Started in #76 for public APIs. 🎉

**Comment by 0x46616c6b** [comment]
Further implementation will tracked in other issues.
